# Topic Modeling 
    Section Goals 
    - Understand Topic Modeling
    - Learn Latent Drichlet Allocation 
    - Implement LDA
    - Understand Non-Negative Matrix  Factorization
    - Implement NMF
    - Apply LDA and NMF with a project
    
    Topic Modeling allows for us to efficiently analyze large volumes of text by clustering documents into topics.    
    A large amount of text data is unlabeled meaning we won't be able to apply our previous supervised learning approaches to
    create machine learning models for the data!

    If we have unlabeled data, then we can attempt to "discover" labels.
    In the case of text data, this means attempting to discover clusters of documents, grouped together by topic.

In [2]:
 import pandas as pd

In [3]:
npr = pd.read_csv('npr.csv')

In [4]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
# npr['Article'][0]

In [6]:
# len(npr)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [9]:
dtm = cv.fit_transform(npr['Article'])

In [10]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.decomposition import LatentDirichletAllocation

In [20]:
lda = LatentDirichletAllocation(n_components=7,random_state=42)

In [22]:
try:
    lda.fit(dtm)
except Exception as e:
    print(e)

In [32]:
# Grab the vocabulary of words
len(cv.get_feature_names_out())

54777

In [36]:
type(cv.get_feature_names_out())

numpy.ndarray

In [40]:
cv.get_feature_names_out()[5000]

'bask'

In [44]:
import random 
random_word_id = random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'cortney'

In [46]:
# Grab the topics
len(lda.components_)

7

In [48]:
lda.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [50]:
single_topic = lda.components_[0]

In [52]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [54]:
import numpy as np

In [56]:
arr = np.array([10,200,1])

In [58]:
arr

array([ 10, 200,   1])

In [60]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [62]:
# ARGSORT ----> INDEX POSITIONS SORTED FROM LEAST ---> GREATEST
# TOP 10 VALUES (10 GREATEST VALUES)
# LAST 10 VALUES OF ARGSORT()
single_topic.argsort()[:10] # grab the last 10 values of . argsort()

array([ 2475, 18302, 35285, 44967, 25943,  8551, 30782, 20015, 26667,
       19712], dtype=int64)

In [64]:
top_ten_words = single_topic.argsort()[-10:]

In [66]:
for index in top_ten_words:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says

In [ ]:
# Grab the highest probability words per topic

In [74]:
for index,topic in enumerate(lda.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']




THE TOP 15 WORDS FOR TOPIC #6
['student', 'years', 'data', 'science', 'university', 'people', 'time', 'schools', 'just', 'education', 'new', 'like', 'students', 'school', 'says']

In [76]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [82]:
topic_results = lda.transform(dtm)

In [86]:
topic_results[0].argmax()

1

In [88]:
npr['Topic'] = topic_results.argmax(axis=1)

In [90]:
npr

                                                 Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]