# Topic Modeling Assessment Project
    Welcome too your Topic Modeling Assessment! For this project you will be working with dataset of over 400,000 quora questions that have no labeled category and attempting to find 20 cateogries to assign questions to. The.csv file of these text questions can be found underneath the Topic-Modeling folder.

<strong> Task : import pandas and read in the quora_questions.csv file </strong>

In [6]:
import pandas as pd

In [8]:
npr = pd.read_csv('../Documents/quora_questions.csv')

In [54]:
npr['Question'][10]

'Method to find separation of slits using fresnel biprism?'

In [10]:
npr.head()

                                            Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

## Preprocessing
<strong> Task : Use TF-IDF Vectorization to create a vectorized document term matrix. You may want to explore the max_df and min_df parameters.</strong>

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [58]:
tfidf = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [60]:
dtm = tfidf.fit_transform(npr['Question'])

In [61]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

## NoN-negative Matrix Factorization 
<strong> Task : Using Scikit-learn create an instance of nmf with 20 expected componets.(user random_state=42)

In [64]:
from sklearn.decomposition import NMF

In [66]:
nmf_model = NMF(n_components=20,random_state=42)

In [70]:
nmf_model.fit(dtm)

C:\Users\Engel\anaconda3\Lib\site-packages\sklearn\decomposition\_nmf.py:1742: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

NMF(n_components=20, random_state=42)

<strong> Task: print our the top 15 most common word for each of the 20 topics.</strong>

In [78]:
for index,topic in enumerate(nmf_model.components_):
    print(f"The top 15 words for topic # {index}")
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

The top 15 words for topic # 0
['thing', 'read', 'place', 'visit', 'places', 'phone', 'buy', 'laptop', 'movie', 'ways', '2016', 'books', 'book', 'movies', 'best']


The top 15 words for topic # 1
['majors', 'recruit', 'sex', 'looking', 'differ', 'use', 'exist', 'really', 'compare', 'cost', 'long', 'feel', 'work', 'mean', 'does']


The top 15 words for topic # 2
['add', 'answered', 'needing', 'post', 'easily', 'improvement', 'delete', 'asked', 'google', 'answers', 'answer', 'ask', 'question', 'questions', 'quora']


The top 15 words for topic # 3
['using', 'website', 'investment', 'friends', 'black', 'internet', 'free', 'home', 'easy', 'youtube', 'ways', 'earn', 'online', 'make', 'money']


The top 15 words for topic # 4
['balance', 'earth', 'day', 'death', 'changed', 'live', 'want', 'change', 'moment', 'real', 'important', 'thing', 'meaning', 'purpose', 'life']


The top 15 words for topic # 5
['reservation', 'engineering', 'minister', 'president', 'company', 'china', 'business', 'country', 'olympics', 'available', 'job', 'spotify', 'war', 'pakistan', 'india']


The top 15 words for topic # 6
['beginners', 'online', 'english', 'book', 'did', 'hacking', 'want', 'python', 'languages', 'java', 'learning', 'start', 'language', 'programming', 'learn']


The top 15 words for topic # 7
['happen', 'presidency', 'think', 'presidential', '2016', 'vote', 'better', 'election', 'did', 'win', 'hillary', 'president', 'clinton', 'donald', 'trump']


The top 15 words for topic # 8
['russia', 'business', 'win', 'coming', 'countries', 'place', 'pakistan', 'happen', 'end', 'country', 'iii', 'start', 'did', 'war', 'world']


The top 15 words for topic # 9
['indian', 'companies', 'don', 'guy', 'men', 'culture', 'women', 'work', 'girls', 'live', 'girl', 'look', 'sex', 'feel', 'like']


The top 15 words for topic # 10
['ca', 'departments', 'positions', 'movies', 'songs', 'business', 'read', 'start', 'job', 'work', 'engineering', 'ways', 'bad', 'books', 'good']


The top 15 words for topic # 11
['money', 'modi', 'currency', 'economy', 'think', 'government', 'ban', 'banning', 'black', 'indian', 'rupee', 'rs', '1000', 'notes', '500']


The top 15 words for topic # 12
['blowing', 'resolutions', 'resolution', 'mind', 'likes', 'girl', '2017', 'year', 'don', 'employees', 'going', 'day', 'things', 'new', 'know']


The top 15 words for topic # 13
['aspects', 'fluent', 'skill', 'spoken', 'ways', 'language', 'fluently', 'speak', 'communication', 'pronunciation', 'speaking', 'writing', 'skills', 'improve', 'english']


The top 15 words for topic # 14
['diet', 'help', 'healthy', 'exercise', 'month', 'pounds', 'reduce', 'quickly', 'loss', 'fast', 'fat', 'ways', 'gain', 'lose', 'weight']


The top 15 words for topic # 15
['having', 'feel', 'long', 'spend', 'did', 'person', 'machine', 'movies', 'favorite', 'job', 'home', 'sex', 'possible', 'travel', 'time']


The top 15 words for topic # 16
['marriage', 'make', 'did', 'girlfriend', 'feel', 'tell', 'forget', 'really', 'friend', 'true', 'know', 'person', 'girl', 'fall', 'love']


The top 15 words for topic # 17
['easy', 'hack', 'prepare', 'quickest', 'facebook', 'increase', 'painless', 'instagram', 'account', 'best', 'commit', 'fastest', 'suicide', 'easiest', 'way']


The top 15 words for topic # 18
['web', 'java', 'scripting', 'phone', 'mechanical', 'better', 'job', 'use', 'account', 'data', 'software', 'science', 'computer', 'engineering', 'difference']


The top 15 words for topic # 19
['earth', 'blowing', 'stop', 'use', 'easily', 'mind', 'google', 'flat', 'questions', 'hate', 'believe', 'ask', 'don', 'think', 'people']

<strong>Task: Add a new column to the original quora dataframe that labels each question into one of the 20 topic categories</strong>

In [82]:
topic_results = nmf_model.transform(dtm)

In [84]:
npr['Topic'] = topic_results.argmax(axis=1)

In [86]:
npr.head()

                                            Question  Topic
0  What is the step by step guide to invest in sh...      5
1  What is the story of Kohinoor (Koh-i-Noor) Dia...     16
2  How can I increase the speed of my internet co...     17
3  Why am I mentally very lonely? How can I solve...     11
4  Which one dissolve in water quikly sugar, salt...     14